- name: Install catalogue component
  hosts: catalogue
  become: yes
  tasks:
  - name: set npm source
    ansible.builtin.script: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  - name: Install nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed