- name: Install mongodb
  hosts: mongodb
  become: yes
  tasks:
    - name: copy mango repo to yum
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongo.repo
    - name: Install mongodb
      ansible.builtin.yum:
        name: mongodb-org
        state: installed
    - name: enable and restart service
      ansible.builtin.service:
        state: started
        enable: yes