- name: Install rabbitmq component
  hosts: rabbitmq
  become: yes
  tasks:
  - name: Install rabbitmq repo
    ansible.builtin.shell: "{{item}}"
    loop:
    - "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
    - "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"

  - name: Install rabbitmq
    ansible.builtin.yum:
     name: rabbitmq-server
     state: installed

  - name: Start enable rabbitmq service
    ansible.builtin.service:
     name: rabbitmq
     state: started
     enabled: yes

  - name: set username and password for rabbitmq
    ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123

  - name: set permission for rabbitmq
    ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"